In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("Wall robot navigation.csv",sep=",")

In [3]:
data.head()

V1     V2     V3     V4  Class
0  1.687  0.445  2.332  0.429      4
1  1.687  0.449  2.332  0.429      4
2  1.687  0.449  2.334  0.429      4
3  1.687  0.449  2.334  0.429      4
4  1.687  0.449  2.334  0.429      4

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5456 entries, 0 to 5455
Data columns (total 5 columns):
V1       5456 non-null float64
V2       5456 non-null float64
V3       5456 non-null float64
V4       5456 non-null float64
Class    5456 non-null int64
dtypes: float64(4), int64(1)
memory usage: 213.2 KB


##### V1,V2,V3,V4 are the numerical variables. Class is the categorical variable but is given as integer here.

In [5]:
data[['V1','V2','V3','V4']].describe() # Analyzing only the numerical columns

V1           V2           V3           V4
count  5456.000000  5456.000000  5456.000000  5456.000000
mean      1.290307     0.681269     1.881819     1.273689
std       0.626700     0.342594     0.562533     0.821750
min       0.495000     0.340000     0.836000     0.367000
25%       0.826000     0.495000     1.472000     0.788000
50%       1.089500     0.612000     1.753000     1.066500
75%       1.519500     0.753000     2.139000     1.400500
max       5.000000     5.000000     5.000000     5.000000

### Normalization of numerical variables

extracting only the numerical columns so as to normalize it between 0 and 1

In [6]:
df=data[['V1', 'V2', 'V3', 'V4']] # Extracting only the numerical columns to a new dataframe so as to normalize them.

In [7]:
import sklearn

In [8]:
from sklearn import preprocessing

In [9]:
df.columns

Index(['V1', 'V2', 'V3', 'V4'], dtype='object')

In [10]:
x=df.values

In [11]:
x

array([[1.687, 0.445, 2.332, 0.429],
       [1.687, 0.449, 2.332, 0.429],
       [1.687, 0.449, 2.334, 0.429],
       ...,
       [0.873, 0.642, 1.053, 1.105],
       [0.967, 0.635, 1.034, 1.118],
       [0.854, 0.628, 1.016, 1.168]])

In [12]:
min_max_scaler = preprocessing.MinMaxScaler()

In [13]:
x_scaled = min_max_scaler.fit_transform(x)

In [14]:
df_normalized = pd.DataFrame(x_scaled)

In [15]:
df_normalized.head() #normalized dataframe

0         1        2         3
0  0.264595  0.022532  0.35927  0.013382
1  0.264595  0.023391  0.35927  0.013382
2  0.264595  0.023391  0.35975  0.013382
3  0.264595  0.023391  0.35975  0.013382
4  0.264595  0.023391  0.35975  0.013382

In [16]:
df_normalized['class']=data['Class']

In [17]:
df_normalized.head()

0         1        2         3  class
0  0.264595  0.022532  0.35927  0.013382      4
1  0.264595  0.023391  0.35927  0.013382      4
2  0.264595  0.023391  0.35975  0.013382      4
3  0.264595  0.023391  0.35975  0.013382      4
4  0.264595  0.023391  0.35975  0.013382      4

In [18]:
df2=df_normalized

### One hot encoding on the categorical variable which is 'class'

In [19]:
from sklearn.preprocessing import OneHotEncoder

In [20]:
onehotencoder = OneHotEncoder(categorical_features = [4]) # 'class' is column 4

In [21]:
df2 = onehotencoder.fit_transform(df2).toarray()

C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [22]:
df2=pd.DataFrame(df2) #one hot encoded & normalized dataframe 

In [23]:
df2.sample(5)

0    1    2    3         4         5         6         7
1074  0.0  1.0  0.0  0.0  0.060155  0.031330  0.567723  0.203324
4337  0.0  1.0  0.0  0.0  0.066593  0.063948  0.190202  0.092812
2899  1.0  0.0  0.0  0.0  0.219534  0.076609  0.139529  0.074250
4225  1.0  0.0  0.0  0.0  0.129412  0.051502  0.072767  0.173754
5282  1.0  0.0  0.0  0.0  0.390233  0.036481  0.235591  0.234190

# Performing logistic regression to classify

## Process the dataset

In [24]:
data['Class'].value_counts(normalize=1)*100

1    40.414223
2    38.434751
4    15.139296
3     6.011730
Name: Class, dtype: float64

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
# create training and testing variables
X_train, X_test, y_train, y_test = train_test_split(data[['V1','V2','V3','V4']],data['Class'], test_size=0.2,random_state=42,stratify=data['Class'])

In [27]:
print(X_train.shape, y_train.shape)
print(X_test.shape, y_test.shape)

(4364, 4) (4364,)
(1092, 4) (1092,)


### Using logistic regression

In [28]:
from sklearn.linear_model import LogisticRegression 
from sklearn.metrics import accuracy_score

In [29]:
model = LogisticRegression()

In [30]:
model.fit(X_train,y_train)

C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [31]:
predicted_class=model.predict(X_test)

In [32]:
accuracy = accuracy_score(y_test,predicted_class)

In [33]:
accuracy

0.8205128205128205

In [34]:
from sklearn.metrics import classification_report

In [35]:
print(classification_report(y_test,predicted_class))

              precision    recall  f1-score   support

           1       0.75      0.88      0.81       441
           2       0.87      0.98      0.92       420
           3       0.89      0.83      0.86        66
           4       1.00      0.25      0.41       165

   micro avg       0.82      0.82      0.82      1092
   macro avg       0.88      0.74      0.75      1092
weighted avg       0.84      0.82      0.80      1092



In [36]:
from sklearn.metrics import confusion_matrix

In [37]:
cm=confusion_matrix(y_test, predicted_class)

In [38]:
cm

array([[386,  55,   0,   0],
       [  0, 413,   7,   0],
       [  5,   6,  55,   0],
       [123,   0,   0,  42]], dtype=int64)

## Classification using neural network model

In [39]:
from sklearn.neural_network import MLPClassifier

In [40]:
nnmodel = MLPClassifier(hidden_layer_sizes=(100,50))

In [41]:
nnmodel.fit(X_train,y_train)

C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(100, 50), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [42]:
nnpredicted_class=nnmodel.predict(X_test)

In [43]:
accuracy_score(y_test,nnpredicted_class)

0.9853479853479854

In [44]:
print(classification_report(y_test,nnpredicted_class))

              precision    recall  f1-score   support

           1       0.99      0.98      0.98       441
           2       1.00      0.99      0.99       420
           3       0.97      0.97      0.97        66
           4       0.96      1.00      0.98       165

   micro avg       0.99      0.99      0.99      1092
   macro avg       0.98      0.98      0.98      1092
weighted avg       0.99      0.99      0.99      1092



In [45]:
nn_cm=confusion_matrix(y_test, nnpredicted_class)

In [46]:
nn_cm

array([[433,   1,   1,   6],
       [  4, 414,   1,   1],
       [  2,   0,  64,   0],
       [  0,   0,   0, 165]], dtype=int64)

### Finding out the false postive rate & false negative rate for both the methods - Logistic regression & Multi-layer neural network

In [47]:
import numpy as np

In [48]:
def false_perc(matrix):
    FP = matrix.sum(axis=0) - np.diag(matrix)
    FN = matrix.sum(axis=1) - np.diag(matrix)
    TP = np.diag(matrix)
    TN = matrix.sum() - (FP + FN + TP)
    FP = FP.astype(float)
    FN = FN.astype(float)
    TP = TP.astype(float)
    TN = TN.astype(float)
    FPR = FP/(FP+TN) # FPR - False Positive Rate
    FNR = FN/(TP+FN) # FNR - False Negative Rate
    fr=np.vstack((FPR,FNR))
    fr=fr*100
    false_rate=pd.DataFrame(fr,columns=[1,2,3,4],index=['FPR(%)','FNR(%)'])
    print(false_rate)

In [49]:
false_perc(cm) # for logistic regression

                1         2          3          4
FPR(%)  19.662058  9.077381   0.682261   0.000000
FNR(%)  12.471655  1.666667  16.666667  74.545455


In [50]:
false_perc(nn_cm) # for neural network

               1         2         3         4
FPR(%)  0.921659  0.148810  0.194932  0.755124
FNR(%)  1.814059  1.428571  3.030303  0.000000


### Experimenting the neural network model with different number of hidden layers and nodes 

In [51]:
nnmodel = MLPClassifier(hidden_layer_sizes=(100,50,20))
nnmodel.fit(X_train,y_train)
nnpredicted_class=nnmodel.predict(X_test)
accuracy_score(y_test,nnpredicted_class)

0.9688644688644689

The accuracy has decreased compared to that of the previous one. Hence a 3rd hidden layer is not required. 

In [52]:
nnmodel = MLPClassifier(hidden_layer_sizes=(100,30))
nnmodel.fit(X_train,y_train)
nnpredicted_class=nnmodel.predict(X_test)
accuracy_score(y_test,nnpredicted_class)

0.9853479853479854

Accuracy remains almost the same

In [53]:
nnmodel = MLPClassifier(hidden_layer_sizes=(100,60))
nnmodel.fit(X_train,y_train)
nnpredicted_class=nnmodel.predict(X_test)
accuracy_score(y_test,nnpredicted_class)

C:\Users\VAISHAK\Anaconda3\lib\site-packages\sklearn\neural_network\multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


0.9862637362637363

Accuracy has increased slightly.

In [54]:
nnmodel = MLPClassifier(hidden_layer_sizes=(100,100))
nnmodel.fit(X_train,y_train)
nnpredicted_class=nnmodel.predict(X_test)
accuracy_score(y_test,nnpredicted_class)

0.989010989010989

The accuracy has increased even further. This seems to be a good model.